---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: pure-csi
  labels:
    kubeaddons.mesosphere.io/name: pure-csi-1.0.8
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.4.0-1"
    appversion.kubeaddons.mesosphere.io/pure-csi-1.0.8: "0.4.0"
    values.chart.helm.kubeaddons.mesosphere.io/pure-csi-1.0.8: "https://raw.githubusercontent.com/mesosphere/charts/6c43b8ab10108fb1adba5c6dd10e800e5f1abdd0/stable/pure-csi-1.0.8/values.yaml"
spec:
  namespace: pure-flash
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: defaultstorageclass-protection
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
  chartReference:
    chart: pure-csi-1.0.8
    repo: https://purestorage.github.io/helm-charts
    version: 1.0.8
    values: |
      ---
      resizer:
        enabled: false
      snapshotter:
        enabled: true
      provisioner:
        enableVolumeScheduling: true
      storageclass:
        isDefault: true

