---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: pure-csi
  labels:
    kubeaddons.mesosphere.io/name: pure-csi
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "5.0.8"
    appversion.kubeaddons.mesosphere.io/pure-csi: "1.0.8"
    values.chart.helm.kubeaddons.mesosphere.io/pure-csi: "https://github.com/purestorage/helm-charts/blob/master/pure-csi/values.yaml"
spec:
  namespace: pure-csi
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: defaultstorageclass-protection
  kubernetes:
    minSupportedVersion: v1.15.6
  storageProvider:
    - name: pure
      enabled: true
  chartReference:
    chart: pure/pure-csi
    repo: https://purestorage.github.io/helm-charts
    version: 1.0.8
    values: |
      ---
      storageclass:  
        isPureDefault: true
        pureBackend: pure-file
      arrays:
        FlashArrays:
          - MgmtEndPoint: "1.2.3.4"
            APIToken: "a526a4c6-18b0-a8c9-1afa-3499293574bb"
          - MgmtEndPoint: "1.2.3.5"
            APIToken: "b526a4c6-18b0-a8c9-1afa-3499293574bb"
        FlashBlades:
          - MgmtEndPoint: "1.2.3.6"
            APIToken: "T-c4925090-c9bf-4033-8537-d24ee5669135"
            NfsEndPoint: "1.2.3.7"
